# SMS Hub Web - Remote Supabase Configuration
# This project uses remote-only Supabase connections
# Dev: hmumtnpnyxuplvqcmnfk (web-dev)
# Prod: fwlivygerbqzowbzxesw (web-prod)

project_id = "web-dev"

# Remote-only configuration - no local services
# Note: These sections are commented out for remote-only usage
# [api]
# enabled = true
# port = 54321

# [db]
# enabled = true
# port = 54322

# [studio]
# enabled = true
# port = 54323

# [inbucket]
# enabled = true
# port = 54324

# [auth]
# enabled = true

# All authentication and database operations use remote Supabase instances
# Dev: https://hmumtnpnyxuplvqcmnfk.supabase.co
# Prod: https://fwlivygerbqzowbzxesw.supabase.co

[functions.submit-contact]
enabled = true
verify_jwt = false

[functions.stripe-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/stripe-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/stripe-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/stripe-webhook/*.html" ]
