# SMS Hub Monorepo - Remote Supabase Configuration
# This project uses remote-only Supabase connections
# Dev: vgpovgpwqkjnpnrjelyg (sms-hub-monorepo)
# Prod: howjinnvvtvaufihwers (percytech)

project_id = "sms-hub-monorepo"

# Remote-only configuration - no local services
# Note: These sections are commented out for remote-only usage
# [api]
# enabled = true
# port = 54321

# [db]
# enabled = true
# port = 54322

# [studio]
# enabled = true
# port = 54323

# [inbucket]
# enabled = true
# port = 54324

# [auth]
# enabled = true

# All authentication and database operations use remote Supabase instances
# Development: https://vgpovgpwqkjnpnrjelyg.supabase.co
# Production: https://howjinnvvtvaufihwers.supabase.co


[functions.tcr-register-campaign]
enabled = true
verify_jwt = true
import_map = "./functions/tcr-register-campaign/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/tcr-register-campaign/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/tcr-register-campaign/*.html" ]

[functions.tcr-webhook]
enabled = true
verify_jwt = true
import_map = "./functions/tcr-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/tcr-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/tcr-webhook/*.html" ]

[functions.stripe-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/stripe-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/stripe-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/stripe-webhook/*.html" ]
